plugins {
    id 'java'
}

apply plugin: 'application'

mainClassName = 'com.multi.travel'

group = 'com.multi'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile){
    options.encoding = 'UTF-8'
}
tasks.withType(Test){
    systemProperty 'file.encoding', 'UTF-8'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'com.mysql:mysql-connector-j:8.4.0'
    implementation 'com.opencsv:opencsv:5.5'
}

test {
    useJUnitPlatform()
}

run {
    jvmArgs = ['-Dfile.encoding=UTF-8']
}
